import { Agreement, Partner, Statistics } from './types';

export const mockStatistics: Statistics = {
  totalVisits: 1250,
  activeAgreements: 45,
  activePartners: 23,
  recentDocuments: 12,
};

export const mockAgreements: Agreement[] = [
  {
    id: '1',
    title: 'Accord Cadre UAC-UNESCO',
    type: 'Accord cadre',
    domain: 'Sciences de la Santé',
    country: 'France',
    countryCode: 'FR',
    startDate: '2023-03-15',
    endDate: '2026-03-15',
    status: 'En cours',
    signatureDate: '2023-03-15',
    partners: ['UNESCO', 'Université de Paris'],
    documents: [
      {
        id: '1',
        name: 'Accord.pdf',
        type: 'pdf',
        url: 'https://example.com/accord.pdf',
        size: '2.5 MB',
      },
      {
        id: '2',
        name: 'Annexe.docx',
        type: 'docx',
        url: 'https://example.com/annexe.docx',
        size: '1.2 MB',
      },
    ],
    description: 'Accord de coopération dans le domaine des sciences de la santé avec l\'UNESCO.',
  },
  {
    id: '2',
    title: 'Convention UAC-USAID',
    type: 'Convention',
    domain: 'Sciences et Technologies',
    country: 'États-Unis',
    countryCode: 'US',
    startDate: '2022-01-10',
    endDate: '2025-01-10',
    status: 'En cours',
    signatureDate: '2022-01-10',
    partners: ['USAID', 'MIT'],
    documents: [
      {
        id: '3',
        name: 'Convention.pdf',
        type: 'pdf',
        url: 'https://example.com/convention.pdf',
        size: '3.1 MB',
      },
    ],
    description: 'Convention de coopération technologique avec USAID.',
  },
  {
    id: '3',
    title: 'Accord UAC-Université de Toronto',
    type: 'Coopération',
    domain: 'Sciences Agronomiques',
    country: 'Canada',
    countryCode: 'CA',
    startDate: '2021-09-01',
    endDate: '2024-09-01',
    status: 'En cours',
    signatureDate: '2021-09-01',
    partners: ['Université de Toronto'],
    documents: [
      {
        id: '4',
        name: 'Coopération.pdf',
        type: 'pdf',
        url: 'https://example.com/cooperation.pdf',
        size: '1.8 MB',
      },
    ],
    description: 'Accord de coopération en sciences agronomiques.',
  },
  {
    id: '4',
    title: 'Convention UAC-Université de Berlin',
    type: 'Convention',
    domain: 'Sciences de la Santé',
    country: 'Allemagne',
    countryCode: 'DE',
    startDate: '2020-05-15',
    endDate: '2023-05-15',
    status: 'Expiré',
    signatureDate: '2020-05-15',
    partners: ['Université de Berlin'],
    documents: [
      {
        id: '5',
        name: 'Convention_Berlin.pdf',
        type: 'pdf',
        url: 'https://example.com/berlin.pdf',
        size: '2.2 MB',
      },
    ],
    description: 'Convention expirée avec l\'Université de Berlin.',
  },
  {
    id: '5',
    title: 'Accord UAC-Université de Tokyo',
    type: 'Accord cadre',
    domain: 'Sciences et Technologies',
    country: 'Japon',
    countryCode: 'JP',
    startDate: '2023-07-01',
    endDate: '2026-07-01',
    status: 'En cours',
    signatureDate: '2023-07-01',
    partners: ['Université de Tokyo', 'RIKEN'],
    documents: [
      {
        id: '6',
        name: 'Accord_Tokyo.pdf',
        type: 'pdf',
        url: 'https://example.com/tokyo.pdf',
        size: '2.8 MB',
      },
    ],
    description: 'Accord cadre avec l\'Université de Tokyo pour la recherche technologique.',
  },
  {
    id: '6',
    title: 'Convention UAC-Université de Cambridge',
    type: 'Convention',
    domain: 'Sciences Économiques',
    country: 'Royaume-Uni',
    countryCode: 'GB',
    startDate: '2022-11-20',
    endDate: '2025-11-20',
    status: 'En cours',
    signatureDate: '2022-11-20',
    partners: ['Université de Cambridge'],
    documents: [
      {
        id: '7',
        name: 'Convention_Cambridge.pdf',
        type: 'pdf',
        url: 'https://example.com/cambridge.pdf',
        size: '1.9 MB',
      },
    ],
    description: 'Convention de coopération en sciences économiques.',
  },
  {
    id: '7',
    title: 'Accord UAC-Université de Rome',
    type: 'Accord cadre',
    domain: 'Sciences Juridiques',
    country: 'Italie',
    countryCode: 'IT',
    startDate: '2023-01-15',
    endDate: '2026-01-15',
    status: 'En cours',
    signatureDate: '2023-01-15',
    partners: ['Université de Rome La Sapienza'],
    documents: [
      {
        id: '8',
        name: 'Accord_Rome.pdf',
        type: 'pdf',
        url: 'https://example.com/rome.pdf',
        size: '2.1 MB',
      },
    ],
    description: 'Accord cadre en sciences juridiques.',
  },
  {
    id: '8',
    title: 'Convention UAC-Université de Madrid',
    type: 'Convention',
    domain: 'Sciences Sociales',
    country: 'Espagne',
    countryCode: 'ES',
    startDate: '2021-06-10',
    endDate: '2024-06-10',
    status: 'Reconduction tacite',
    signatureDate: '2021-06-10',
    partners: ['Université Complutense de Madrid'],
    documents: [
      {
        id: '9',
        name: 'Convention_Madrid.pdf',
        type: 'pdf',
        url: 'https://example.com/madrid.pdf',
        size: '1.7 MB',
      },
    ],
    description: 'Convention en sciences sociales.',
  },
];

export const mockPartners: Partner[] = [
  {
    id: '1',
    name: 'France',
    country: 'France',
    countryCode: 'FR',
    latitude: 46.2276,
    longitude: 2.2137,
    agreementsCount: 5,
    flag: '🇫🇷',
  },
  {
    id: '2',
    name: 'États-Unis',
    country: 'États-Unis',
    countryCode: 'US',
    latitude: 39.8283,
    longitude: -98.5795,
    agreementsCount: 3,
    flag: '🇺🇸',
  },
  {
    id: '3',
    name: 'Canada',
    country: 'Canada',
    countryCode: 'CA',
    latitude: 56.1304,
    longitude: -106.3468,
    agreementsCount: 2,
    flag: '🇨🇦',
  },
  {
    id: '4',
    name: 'Allemagne',
    country: 'Allemagne',
    countryCode: 'DE',
    latitude: 51.1657,
    longitude: 10.4515,
    agreementsCount: 1,
    flag: '��🇪',
  },
  {
    id: '5',
    name: 'Japon',
    country: 'Japon',
    countryCode: 'JP',
    latitude: 36.2048,
    longitude: 138.2529,
    agreementsCount: 4,
    flag: '🇯🇵',
  },
  {
    id: '6',
    name: 'Royaume-Uni',
    country: 'Royaume-Uni',
    countryCode: 'GB',
    latitude: 55.3781,
    longitude: -3.4360,
    agreementsCount: 2,
    flag: '🇬🇧',
  },
  {
    id: '7',
    name: 'Italie',
    country: 'Italie',
    countryCode: 'IT',
    latitude: 41.8719,
    longitude: 12.5674,
    agreementsCount: 1,
    flag: '🇮🇹',
  },
  {
    id: '8',
    name: 'Espagne',
    country: 'Espagne',
    countryCode: 'ES',
    latitude: 40.4637,
    longitude: -3.7492,
    agreementsCount: 1,
    flag: '🇪🇸',
  },
  {
    id: '9',
    name: 'Brésil',
    country: 'Brésil',
    countryCode: 'BR',
    latitude: -14.2350,
    longitude: -51.9253,
    agreementsCount: 3,
    flag: '🇧��',
  },
  {
    id: '10',
    name: 'Chine',
    country: 'Chine',
    countryCode: 'CN',
    latitude: 35.8617,
    longitude: 104.1954,
    agreementsCount: 2,
    flag: '🇨🇳',
  },
  {
    id: '11',
    name: 'Inde',
    country: 'Inde',
    countryCode: 'IN',
    latitude: 20.5937,
    longitude: 78.9629,
    agreementsCount: 1,
    flag: '🇮🇳',
  },
  {
    id: '12',
    name: 'Afrique du Sud',
    country: 'Afrique du Sud',
    countryCode: 'ZA',
    latitude: -30.5595,
    longitude: 22.9375,
    agreementsCount: 2,
    flag: '🇿🇦',
  },
];

export const domains = [
  'Sciences de la Santé',
  'Sciences et Technologies',
  'Sciences Agronomiques',
  'Sciences Économiques',
  'Sciences Juridiques',
  'Sciences Sociales',
];

export const agreementTypes = [
  'Accord cadre',
  'Convention',
  'Coopération',
];

export const countries = [
  { name: 'France', code: 'FR', flag: '🇫🇷' },
  { name: 'États-Unis', code: 'US', flag: '🇺🇸' },
  { name: 'Canada', code: 'CA', flag: '🇨🇦' },
  { name: 'Allemagne', code: 'DE', flag: '��🇪' },
  { name: 'Japon', code: 'JP', flag: '🇯🇵' },
  { name: 'Royaume-Uni', code: 'GB', flag: '��🇧' },
  { name: 'Italie', code: 'IT', flag: '🇮��' },
  { name: 'Espagne', code: 'ES', flag: '🇪🇸' },
  { name: 'Brésil', code: 'BR', flag: '🇧🇷' },
  { name: 'Chine', code: 'CN', flag: '🇨🇳' },
  { name: 'Inde', code: 'IN', flag: '🇮🇳' },
  { name: 'Afrique du Sud', code: 'ZA', flag: '🇿🇦' },
];
